<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gramaticajmeter" nsURI="http://www.edu.co/uniandes/Gramaticajmeter"
    nsPrefix="gramaticajmeter">
  <eClassifiers xsi:type="ecore:EClass" name="JMeter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="architectureResults" upperBound="-1"
        eType="#//ArchitectureResults" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureResults">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="architecture" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//Header"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//Results" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headerJMeter" eType="#//HeaderJMeter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultsJMeter" upperBound="-1"
        eType="#//Results" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Results">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" upperBound="-1"
        eType="#//Result" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Result">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeaderJMeter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
